apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jim-gitops
  description: This is GitOps manifest for jim   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jim
    janus-idp.io/tekton: jim 
    backstage.io/kubernetes-id: jim 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jim
