apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jim
  janus-idp.io/tekton: jim
  backstage.io/kubernetes-id: jim
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jim
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml 
